### ISSUE TITLE
Add filter bar to articles page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#192]
Please make all visual / functional enhancements to the homepage so that it is an exact copy to the design concept provided below.

**PSD FIle:**
[HomePage.zip](https://github.com/BattlePro/battlepro-issues/files/1729459/HomePage.zip)

**Notes:**
- When a tournament is 'featured' then it will get promoted to the homepage too
- Gradient is at 75 degrees and 75% opacity for the larger image articles with text overlays.
- Gradient of main article is at 90 degrees so that you can read the 'view article' button clearly

Homepage Design:
![homepage](https://user-images.githubusercontent.com/6005869/36281765-df4121f0-126c-11e8-8111-563560c8531a.jpg)

**Comment by mikecreuzer** [comment]
@Ian-Hitt Nik would like this prioritized. Get tabs working without Jake if you can, just direct links to categories if possible.

**Comment by Ian-Hitt** [comment]
@NikAlexander every article has to be featured, otherwise it cannot have an image. Also, the 4 items you mentioned (latest, announcements, news, tournaments) all need to be categories. I have made them on the live site, but you will need to use them every time you create an article (assuming you want that article to be associated with a category.)

https://www.test.battlepro.com/articles/
